### **Import Pipeline from transformers to perform various Tasks**

### **Sentiment Analysis**

In [1]:
from transformers import pipeline
classifier=pipeline("sentiment-analysis")

2025-05-27 09:40:22.477905: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1748338822.648069      35 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1748338822.699712      35 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Device set to use cuda:0


In [2]:
tasks=classifier([
    "I'm learning Hugging Face course nowadays and this course is very great and i've learned a lot from this course",
    "But Balancing work and learning has been quite exhausting lately"
])
print(tasks)

[{'label': 'POSITIVE', 'score': 0.9998230338096619}, {'label': 'NEGATIVE', 'score': 0.9888855218887329}]


### **Check labels and their Scores**

In [3]:
for task in tasks:
  Labels=task["label"]
  Scores=task["score"]
  print("Labels: ",Labels, '---->', "Score: ", Scores)

Labels:  POSITIVE ----> Score:  0.9998230338096619
Labels:  NEGATIVE ----> Score:  0.9888855218887329


### **Initializing the Tokenizer**

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
tokenizer=AutoTokenizer.from_pretrained("google-bert/bert-base-cased")

In [5]:
# print the tokenization text
print(tokenizer)

BertTokenizerFast(name_or_path='google-bert/bert-base-cased', vocab_size=28996, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
)


### **preprocessing with tokenizer**

In [6]:
tasks=tokenizer([
    "I'm learning Hugging Face course nowadays and this course is very great and i've learned a lot from this course",
    "But Balancing work and learning has been quite exhausting lately"
])
print(tasks)

{'input_ids': [[101, 146, 112, 182, 3776, 20164, 10932, 10289, 1736, 20148, 1105, 1142, 1736, 1110, 1304, 1632, 1105, 178, 112, 1396, 3560, 170, 1974, 1121, 1142, 1736, 102], [101, 1252, 18757, 24855, 1250, 1105, 3776, 1144, 1151, 2385, 16287, 1158, 10634, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}


In [7]:
print(tasks["input_ids"])

[[101, 146, 112, 182, 3776, 20164, 10932, 10289, 1736, 20148, 1105, 1142, 1736, 1110, 1304, 1632, 1105, 178, 112, 1396, 3560, 170, 1974, 1121, 1142, 1736, 102], [101, 1252, 18757, 24855, 1250, 1105, 3776, 1144, 1151, 2385, 16287, 1158, 10634, 102]]


In [8]:
for key in tasks:
  print("Input ids", tasks["input_ids"])
  print("keys", key)
  print("Token type ids", tasks["token_type_ids"])
  print("Attention Mask", tasks["attention_mask"])

Input ids [[101, 146, 112, 182, 3776, 20164, 10932, 10289, 1736, 20148, 1105, 1142, 1736, 1110, 1304, 1632, 1105, 178, 112, 1396, 3560, 170, 1974, 1121, 1142, 1736, 102], [101, 1252, 18757, 24855, 1250, 1105, 3776, 1144, 1151, 2385, 16287, 1158, 10634, 102]]
keys input_ids
Token type ids [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
Attention Mask [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
Input ids [[101, 146, 112, 182, 3776, 20164, 10932, 10289, 1736, 20148, 1105, 1142, 1736, 1110, 1304, 1632, 1105, 178, 112, 1396, 3560, 170, 1974, 1121, 1142, 1736, 102], [101, 1252, 18757, 24855, 1250, 1105, 3776, 1144, 1151, 2385, 16287, 1158, 10634, 102]]
keys token_type_ids
Token type ids [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
Attention Mask [[1

In [9]:
raw_text=[
    "I just completed my first NLP model thanks to this course, and it feels amazing!",
    "This course is structured so well, it's the best learning experience I've had online.",
    "The pace is too fast, and I feel completely lost after the first few lessons."
]
input=tokenizer(raw_text, padding=True, truncation=True, return_tensors="pt")
print(input)


{'input_ids': tensor([[  101,   146,  1198,  2063,  1139,  1148, 21239,  2101,  2235,  5438,
          1106,  1142,  1736,   117,  1105,  1122,  5115,  6929,   106,   102,
             0,     0],
        [  101,  1188,  1736,  1110, 15695,  1177,  1218,   117,  1122,   112,
           188,  1103,  1436,  3776,  2541,   146,   112,  1396,  1125,  3294,
           119,   102],
        [  101,  1109,  6418,  1110,  1315,  2698,   117,  1105,   146,  1631,
          2423,  1575,  1170,  1103,  1148,  1374,  8497,   119,   102,     0,
             0,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1,

In [10]:
for key in input:
  print("Input ids", input["input_ids"])
  print("keys", key)
  print("Token type ids", input["token_type_ids"])
  print("Attention Mask", input["attention_mask"])

Input ids tensor([[  101,   146,  1198,  2063,  1139,  1148, 21239,  2101,  2235,  5438,
          1106,  1142,  1736,   117,  1105,  1122,  5115,  6929,   106,   102,
             0,     0],
        [  101,  1188,  1736,  1110, 15695,  1177,  1218,   117,  1122,   112,
           188,  1103,  1436,  3776,  2541,   146,   112,  1396,  1125,  3294,
           119,   102],
        [  101,  1109,  6418,  1110,  1315,  2698,   117,  1105,   146,  1631,
          2423,  1575,  1170,  1103,  1148,  1374,  8497,   119,   102,     0,
             0,     0]])
keys input_ids
Token type ids tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
Attention Mask tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1,

### **Initializing the AutoModelForSequenceClassification**

In [ ]:
from transformers import AutoModel, AutoModelForSequenceClassification
model=AutoModel.from_pretrained("bert-base-uncased")

In [12]:
model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False

### **Model Inference**

In [13]:
output=model(**input)
output

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-0.6529, -0.0590, -0.2047,  ...,  0.0997,  0.3205,  0.4848],
         [-0.1749, -0.0310, -0.0763,  ..., -0.1239,  0.1651,  0.1732],
         [-0.3366, -0.0607,  0.4245,  ...,  0.2330,  0.1745,  0.1222],
         ...,
         [ 0.3769,  0.1352, -0.3995,  ...,  0.1589, -0.4545, -0.2293],
         [-0.4789, -0.1506, -0.4105,  ...,  0.1330,  0.1464,  0.1058],
         [-0.4601, -0.1313, -0.3631,  ...,  0.1185,  0.0938,  0.0865]],

        [[-0.2786,  0.2764,  0.1395,  ...,  0.0683,  0.2214,  0.4002],
         [-0.0067,  0.4242,  0.2066,  ..., -0.0732,  0.9418,  0.9121],
         [ 0.1281,  0.3166,  0.2722,  ...,  0.0143,  0.1658, -0.1166],
         ...,
         [ 0.1668,  0.3143,  0.4670,  ...,  0.1749,  0.1529,  0.1949],
         [-0.0364, -0.3749,  0.2296,  ...,  0.0761,  0.2537, -0.0946],
         [ 0.3990,  0.3977, -0.3980,  ...,  0.4265, -0.7808, -0.3104]],

        [[-0.3194,  0.1183,  0.1727,  ..., -0.0189,  

### **Let's Check the Hidden State**

In [14]:
output.last_hidden_state

tensor([[[-0.6529, -0.0590, -0.2047,  ...,  0.0997,  0.3205,  0.4848],
         [-0.1749, -0.0310, -0.0763,  ..., -0.1239,  0.1651,  0.1732],
         [-0.3366, -0.0607,  0.4245,  ...,  0.2330,  0.1745,  0.1222],
         ...,
         [ 0.3769,  0.1352, -0.3995,  ...,  0.1589, -0.4545, -0.2293],
         [-0.4789, -0.1506, -0.4105,  ...,  0.1330,  0.1464,  0.1058],
         [-0.4601, -0.1313, -0.3631,  ...,  0.1185,  0.0938,  0.0865]],

        [[-0.2786,  0.2764,  0.1395,  ...,  0.0683,  0.2214,  0.4002],
         [-0.0067,  0.4242,  0.2066,  ..., -0.0732,  0.9418,  0.9121],
         [ 0.1281,  0.3166,  0.2722,  ...,  0.0143,  0.1658, -0.1166],
         ...,
         [ 0.1668,  0.3143,  0.4670,  ...,  0.1749,  0.1529,  0.1949],
         [-0.0364, -0.3749,  0.2296,  ...,  0.0761,  0.2537, -0.0946],
         [ 0.3990,  0.3977, -0.3980,  ...,  0.4265, -0.7808, -0.3104]],

        [[-0.3194,  0.1183,  0.1727,  ..., -0.0189,  0.2487,  0.5928],
         [ 0.3904, -0.0677,  0.5205,  ..., -0

### **Loading Tokenizer and Model for Sequence Classification**

In [ ]:
new_tokenizer=AutoTokenizer.from_pretrained("bert-base-uncased")
new_model=AutoModelForSequenceClassification.from_pretrained("bert-base-uncased")


In [16]:
print(new_tokenizer(raw_text))
new_output=new_model(**input)
print(new_output)

{'input_ids': [[101, 1045, 2074, 2949, 2026, 2034, 17953, 2361, 2944, 4283, 2000, 2023, 2607, 1010, 1998, 2009, 5683, 6429, 999, 102], [101, 2023, 2607, 2003, 14336, 2061, 2092, 1010, 2009, 1005, 1055, 1996, 2190, 4083, 3325, 1045, 1005, 2310, 2018, 3784, 1012, 102], [101, 1996, 6393, 2003, 2205, 3435, 1010, 1998, 1045, 2514, 3294, 2439, 2044, 1996, 2034, 2261, 8220, 1012, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}
SequenceClassifierOutput(loss=None, logits=tensor([[0.5354, 0.3555],
        [0.5392, 0.4549],
        [0.5721, 0.3091]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)


In [17]:
new_output.logits

tensor([[0.5354, 0.3555],
        [0.5392, 0.4549],
        [0.5721, 0.3091]], grad_fn=<AddmmBackward0>)

### **Pipeline Step#2: Models**

In [ ]:
from transformers import AutoConfig
bert_config=AutoConfig.from_pretrained("bert-base-cased")
distill_bert_config=AutoConfig.from_pretrained("distilbert-base-cased")

In [19]:
print("Bert Config")
print(bert_config)
print("====================================")
print("DistillBert Config")
print(distill_bert_config)

Bert Config
BertConfig {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.51.3",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 28996
}

DistillBert Config
DistilBertConfig {
  "activation": "gelu",
  "architectures": [
    "DistilBertForMaskedLM"
  ],
  "attention_dropout": 0.1,
  "dim": 768,
  "dropout": 0.1,
  "hidden_dim": 3072,
  "initializer_range": 0.02,
  "max_position_embeddings": 512,
  "model_type": "distilbert",
  "n_heads": 12,
  "n_layers": 6,
  "output_past": true,
  "pad_token_id": 0,
  "qa_dropo

### **Build and Initiate Bert Model**

In [20]:
from transformers import BertConfig, BertModel
# building the config
bert_model_config=BertConfig()
# initiate the model
new_bert_model=BertModel(bert_model_config)
output=new_bert_model(**input)
print(output)

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-2.3557,  1.7350, -1.1611,  ...,  0.6837, -0.4149, -0.9941],
         [-1.4234,  1.3277,  0.2434,  ...,  0.2697, -1.2665, -0.3489],
         [-1.7267,  2.0018, -0.8336,  ...,  1.9832, -1.8154,  0.3702],
         ...,
         [-1.7829,  1.0530, -1.1842,  ...,  1.9517, -1.3483,  0.4865],
         [-1.0821,  0.2956, -0.4876,  ...,  0.2326, -0.3483, -0.6182],
         [-2.3543,  0.6995, -0.1474,  ...,  0.6159, -0.9443,  0.0057]],

        [[-1.0242,  2.0135, -1.1730,  ...,  1.2692, -0.6526, -0.3315],
         [-0.7865,  1.9886, -1.2671,  ...,  0.6568, -1.4556, -0.1703],
         [-0.8407,  1.4436, -2.3899,  ...,  1.1073, -0.5180,  0.5062],
         ...,
         [-0.5228,  0.3575, -0.1385,  ...,  1.1955, -1.1996,  1.4138],
         [-1.2562, -0.4586, -1.3502,  ...,  1.5371, -2.1946, -0.2501],
         [-2.2434,  1.5906,  0.5280,  ...,  1.6892, -0.7453,  0.3532]],

        [[-1.7882,  1.9175, -0.3124,  ...,  0.7637, -

### **Bert Model Configuration**

In [21]:
bert_model_config

BertConfig {
  "_attn_implementation_autoset": true,
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.51.3",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

In [ ]:
new_bert_model=BertModel.from_pretrained("bert-base-cased", num_hidden_layers= 12, pad_token_id= -1)

In [23]:
output=new_bert_model(**input)
print(output)

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 0.4253,  0.3248,  0.0430,  ..., -0.2575,  0.3103,  0.1707],
         [ 0.5382, -0.1613,  0.6989,  ..., -0.0964, -0.0568,  0.3808],
         [ 0.2170,  0.2973,  0.5711,  ..., -0.2103,  0.0724,  0.7651],
         ...,
         [ 0.5229,  0.6780,  0.5030,  ..., -0.0231,  0.4312,  0.1336],
         [ 0.0116,  0.4218,  0.1210,  ...,  0.2599,  0.1712,  0.2193],
         [-0.0762,  0.2327,  0.3460,  ...,  0.0439,  0.3603,  0.1510]],

        [[ 0.6200,  0.2703, -0.0238,  ..., -0.2052,  0.2143,  0.2290],
         [ 0.4604, -0.3071,  0.6603,  ..., -0.2155,  0.2643,  0.4050],
         [ 0.1338,  0.3411,  0.2855,  ..., -0.0541, -0.2121,  0.4941],
         ...,
         [ 0.1254,  0.1800,  0.6234,  ...,  0.3937,  0.0403,  0.1280],
         [ 0.7558,  1.1082, -0.0067,  ..., -0.0597,  0.1057, -0.0213],
         [ 0.6842,  1.1525,  0.0021,  ..., -0.0347,  0.0960,  0.0695]],

        [[ 0.3652,  0.1974, -0.1084,  ..., -0.2368,  

In [24]:
bert_model=AutoModel.from_pretrained("bert-base-cased")
new_output=bert_model(**input)
print(new_output)

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 0.4253,  0.3248,  0.0430,  ..., -0.2575,  0.3103,  0.1707],
         [ 0.5382, -0.1613,  0.6989,  ..., -0.0964, -0.0568,  0.3808],
         [ 0.2170,  0.2973,  0.5711,  ..., -0.2103,  0.0724,  0.7651],
         ...,
         [ 0.5229,  0.6780,  0.5030,  ..., -0.0231,  0.4312,  0.1336],
         [ 0.0116,  0.4218,  0.1210,  ...,  0.2599,  0.1712,  0.2193],
         [-0.0762,  0.2327,  0.3460,  ...,  0.0439,  0.3603,  0.1510]],

        [[ 0.6200,  0.2703, -0.0238,  ..., -0.2052,  0.2143,  0.2290],
         [ 0.4604, -0.3071,  0.6603,  ..., -0.2155,  0.2643,  0.4050],
         [ 0.1338,  0.3411,  0.2855,  ..., -0.0541, -0.2121,  0.4941],
         ...,
         [ 0.1254,  0.1800,  0.6234,  ...,  0.3937,  0.0403,  0.1280],
         [ 0.7558,  1.1082, -0.0067,  ..., -0.0597,  0.1057, -0.0213],
         [ 0.6842,  1.1525,  0.0021,  ..., -0.0347,  0.0960,  0.0695]],

        [[ 0.3652,  0.1974, -0.1084,  ..., -0.2368,  

In [25]:
new_output.last_hidden_state

tensor([[[ 0.4253,  0.3248,  0.0430,  ..., -0.2575,  0.3103,  0.1707],
         [ 0.5382, -0.1613,  0.6989,  ..., -0.0964, -0.0568,  0.3808],
         [ 0.2170,  0.2973,  0.5711,  ..., -0.2103,  0.0724,  0.7651],
         ...,
         [ 0.5229,  0.6780,  0.5030,  ..., -0.0231,  0.4312,  0.1336],
         [ 0.0116,  0.4218,  0.1210,  ...,  0.2599,  0.1712,  0.2193],
         [-0.0762,  0.2327,  0.3460,  ...,  0.0439,  0.3603,  0.1510]],

        [[ 0.6200,  0.2703, -0.0238,  ..., -0.2052,  0.2143,  0.2290],
         [ 0.4604, -0.3071,  0.6603,  ..., -0.2155,  0.2643,  0.4050],
         [ 0.1338,  0.3411,  0.2855,  ..., -0.0541, -0.2121,  0.4941],
         ...,
         [ 0.1254,  0.1800,  0.6234,  ...,  0.3937,  0.0403,  0.1280],
         [ 0.7558,  1.1082, -0.0067,  ..., -0.0597,  0.1057, -0.0213],
         [ 0.6842,  1.1525,  0.0021,  ..., -0.0347,  0.0960,  0.0695]],

        [[ 0.3652,  0.1974, -0.1084,  ..., -0.2368,  0.1061,  0.1169],
         [ 0.2221, -0.4938,  0.5226,  ..., -0

In [26]:
bert_model.save_pretrained("/content/bert_model")

### **Using a Transformer model for inference**

In [27]:
sequences = ["Hello!", "Cool", "Nice!"]

encoded_sequences = [
    [101, 7592, 999, 102],
    [101, 4658, 1012, 102],
    [101, 3835, 999, 102],
]

In [28]:
import torch
new_input=torch.tensor(encoded_sequences)
print(new_input)

tensor([[ 101, 7592,  999,  102],
        [ 101, 4658, 1012,  102],
        [ 101, 3835,  999,  102]])


In [ ]:
model=AutoModelForSequenceClassification.from_pretrained("google-bert/bert-base-uncased")

In [30]:
google_bert_output=model(new_input)
print(google_bert_output)

SequenceClassifierOutput(loss=None, logits=tensor([[ 0.0022,  0.4167],
        [ 0.4754,  0.4891],
        [-0.0413,  0.4135]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)


In [31]:
google_bert_output.logits

tensor([[ 0.0022,  0.4167],
        [ 0.4754,  0.4891],
        [-0.0413,  0.4135]], grad_fn=<AddmmBackward0>)

In [32]:
probabilities=torch.nn.functional.softmax(google_bert_output.logits, dim=-1)
print(probabilities)

tensor([[0.3978, 0.6022],
        [0.4966, 0.5034],
        [0.3882, 0.6118]], grad_fn=<SoftmaxBackward0>)


## **Tokenizers**

### **Word Tokenize**

In [33]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
tokenize_text="I'm doing Datascience and ai projects, and now a days I'm doing NLP course"
text_tokenize=tokenize_text.split()
print(text_tokenize)

["I'm", 'doing', 'Datascience', 'and', 'ai', 'projects,', 'and', 'now', 'a', 'days', "I'm", 'doing', 'NLP', 'course']


In [ ]:
tokenizer=AutoTokenizer.from_pretrained("bert-base-cased")

In [35]:
output_text=tokenizer.tokenize(tokenize_text)
print(output_text)

['I', "'", 'm', 'doing', 'Data', '##science', 'and', 'a', '##i', 'projects', ',', 'and', 'now', 'a', 'days', 'I', "'", 'm', 'doing', 'NL', '##P', 'course']


### **Loading and saving**

In [36]:
bert_base_model=AutoModelForSequenceClassification.from_pretrained("bert-base-cased")
output=bert_base_model(**input)
print(output)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


SequenceClassifierOutput(loss=None, logits=tensor([[-0.0144,  0.1376],
        [-0.0040,  0.1376],
        [ 0.0251,  0.1435]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)


In [37]:
outputs = tokenizer("Using a Transformer network is simple")
for key,value in outputs.items():
  print("key: ", key)
  print("value: ", value, end="\n\n")

key:  input_ids
value:  [101, 7993, 170, 13809, 23763, 2443, 1110, 3014, 102]

key:  token_type_ids
value:  [0, 0, 0, 0, 0, 0, 0, 0, 0]

key:  attention_mask
value:  [1, 1, 1, 1, 1, 1, 1, 1, 1]



### **Save bert-base-cased Model**

In [38]:
bert_base_model.save_pretrained("/content/bert_base_new_model")

### **Convert tokens to input ids**

In [39]:
ids=tokenizer.convert_tokens_to_ids(output_text)
print(ids)

[146, 112, 182, 1833, 7154, 22274, 1105, 170, 1182, 3203, 117, 1105, 1208, 170, 1552, 146, 112, 182, 1833, 21239, 2101, 1736]


In [40]:
decode_ids=tokenizer.decode([146, 112, 182, 1833, 7154, 22274, 1105, 170, 1182, 3203, 117, 1105, 1208, 170, 1552, 146, 112, 182, 1833, 21239, 2101, 1736])
print(decode_ids)

I ' m doing Datascience and ai projects, and now a days I ' m doing NLP course


In [41]:
print("IDs: ", ids)
print("Input IDs: ", tokenizer(output_text)["input_ids"])

IDs:  [146, 112, 182, 1833, 7154, 22274, 1105, 170, 1182, 3203, 117, 1105, 1208, 170, 1552, 146, 112, 182, 1833, 21239, 2101, 1736]
Input IDs:  [[101, 146, 102], [101, 112, 102], [101, 182, 102], [101, 1833, 102], [101, 7154, 102], [101, 108, 108, 2598, 102], [101, 1105, 102], [101, 170, 102], [101, 108, 108, 178, 102], [101, 3203, 102], [101, 117, 102], [101, 1105, 102], [101, 1208, 102], [101, 170, 102], [101, 1552, 102], [101, 146, 102], [101, 112, 102], [101, 182, 102], [101, 1833, 102], [101, 21239, 102], [101, 108, 108, 153, 102], [101, 1736, 102]]


### **convert ids to tokens**

In [42]:
tokenizer.convert_ids_to_tokens([146, 112, 182, 1833, 7154, 22274, 1105, 170, 1182, 3203, 117, 1105, 1208, 170, 1552, 146, 112, 182, 1833, 21239, 2101, 1736])

['I',
 "'",
 'm',
 'doing',
 'Data',
 '##science',
 'and',
 'a',
 '##i',
 'projects',
 ',',
 'and',
 'now',
 'a',
 'days',
 'I',
 "'",
 'm',
 'doing',
 'NL',
 '##P',
 'course']

### **Summing Up All Together**

In [43]:
import torch
from transformers import AutoTokenizer, AutoModel, AutoModelForSequenceClassification
checkpoint="distilbert/distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model=AutoModelForSequenceClassification.from_pretrained(checkpoint)
raw_inputs=[
    "I've been waiting for a HuggingFace course my whole life.",
    "I have learned a lot from this course!",
]
inputs=tokenizer.tokenize(raw_inputs)
print(inputs)
# convert tokens to ids
ids = tokenizer.convert_tokens_to_ids(inputs)
print(ids)
input_ids=torch.tensor(ids)
print(input_ids)

['i', "'", 've', 'been', 'waiting', 'for', 'a', 'hugging', '##face', 'course', 'my', 'whole', 'life', '.', 'i', 'have', 'learned', 'a', 'lot', 'from', 'this', 'course', '!']
[1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012, 1045, 2031, 4342, 1037, 2843, 2013, 2023, 2607, 999]
tensor([ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
         2026,  2878,  2166,  1012,  1045,  2031,  4342,  1037,  2843,  2013,
         2023,  2607,   999])


### **Performing Inference with istilbert-base-uncased-finetuned-sst-2-english Pre-trained Model**

In [44]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

checkpoint = "distilbert/distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

raw_inputs = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I have learned a lot from this course!",
]

# Proper tokenization with batching
inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors="pt")

output=model(**inputs)

# Output logits
print(output.logits)


tensor([[-1.5607,  1.6123],
        [-2.9620,  3.0196]], grad_fn=<AddmmBackward0>)


In [45]:
padding_id=100
batched_id=[[200,200,200],
            [200,200,padding_id]]
checkpoint = "distilbert/distilbert-base-uncased-finetuned-sst-2-english"
model=AutoModelForSequenceClassification.from_pretrained(checkpoint)
sequence_1_ids=[[200,200,200]]
sequence_2_ids=[[200,200,200],
            [200,200,tokenizer.pad_token_id]]
print(model(torch.tensor(sequence_1_ids)))
print(model(torch.tensor(sequence_2_ids)))
print(model(torch.tensor(batched_id)))




We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.


SequenceClassifierOutput(loss=None, logits=tensor([[ 1.5694, -1.3895]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)
SequenceClassifierOutput(loss=None, logits=tensor([[ 1.5694, -1.3895],
        [ 1.3373, -1.2163]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)
SequenceClassifierOutput(loss=None, logits=tensor([[ 1.5694, -1.3895],
        [ 0.9907, -0.9139]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)


In [46]:
text_sequence=["I'm doing Huggig Face course",
               "It's content is very good"]
input=tokenizer(raw_text, padding=True, truncation=True, return_tensors="pt")
print(input)

{'input_ids': tensor([[  101,  1045,  2074,  2949,  2026,  2034, 17953,  2361,  2944,  4283,
          2000,  2023,  2607,  1010,  1998,  2009,  5683,  6429,   999,   102,
             0,     0],
        [  101,  2023,  2607,  2003, 14336,  2061,  2092,  1010,  2009,  1005,
          1055,  1996,  2190,  4083,  3325,  1045,  1005,  2310,  2018,  3784,
          1012,   102],
        [  101,  1996,  6393,  2003,  2205,  3435,  1010,  1998,  1045,  2514,
          3294,  2439,  2044,  1996,  2034,  2261,  8220,  1012,   102,     0,
             0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]])}


### **Check Attention Mask and Input ids**

In [47]:
for key in input:
  print(key)
  print(input[key])
  print(input['attention_mask'])
  print(input['input_ids'])

input_ids
tensor([[  101,  1045,  2074,  2949,  2026,  2034, 17953,  2361,  2944,  4283,
          2000,  2023,  2607,  1010,  1998,  2009,  5683,  6429,   999,   102,
             0,     0],
        [  101,  2023,  2607,  2003, 14336,  2061,  2092,  1010,  2009,  1005,
          1055,  1996,  2190,  4083,  3325,  1045,  1005,  2310,  2018,  3784,
          1012,   102],
        [  101,  1996,  6393,  2003,  2205,  3435,  1010,  1998,  1045,  2514,
          3294,  2439,  2044,  1996,  2034,  2261,  8220,  1012,   102,     0,
             0,     0]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]])
tensor([[  101,  1045,  2074,  2949,  2026,  2034, 17953,  2361,  2944,  4283,
          2000,  2023,  2607,  1010,  1998,  2009,  5683,  6429,   999,   102,
             0,     0],
        [  101,  2023,  2607,  2

In [48]:
tokenizer.model_max_length

512

### **Padding**

In [49]:
new_model_input=tokenizer(text_sequence, padding="max_length")
print(new_model_input)
new_model_input_1=tokenizer(text_sequence, padding="longest")
print(new_model_input_1)
new_model_input_2=tokenizer(text_sequence, padding="max_length", max_length=8)
print(new_model_input_2)

{'input_ids': [[101, 1045, 1005, 1049, 2725, 8549, 5856, 2290, 2227, 2607, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,